use MAHI_TUTORIAL
SELECT*FROM STUDENT_INFO

--COUNT
SELECT COUNT(R_NO)FROM STUDENT_INFO

SELECT COUNT(NAME)FROM STUDENT_INFO

--MAX
SELECT MAX(SUBJECT1)FROM STUDENT_INFO
SELECT MAX(AGE)FROM STUDENT_INFO
SELECT MAX(NAME)FROM STUDENT_INFO

--MIN
SELECT MIN(SUBJECT1)FROM STUDENT_INFO

--SUM
SELECT SUM(SUBJECT1)FROM STUDENT_INFO
SELECT SUM(AGE)FROM STUDENT_INFO

--AVG
SELECT AVG(SUBJECT1)FROM STUDENT_INFO



