USE MAHI_TUTORIAL
SELECT*FROM STUDENT_INFO 

--ADDITION
SELECT*FROM STUDENT_INFO WHERE (SUBJECT1+SUBJECT2)>100
SELECT*FROM STUDENT_INFO WHERE (SUBJECT1+SUBJECT2)>30
SELECT*FROM STUDENT_INFO WHERE (SUBJECT1+SUBJECT2)<30

--SUBSTRACTION
SELECT*FROM STUDENT_INFO WHERE (SUBJECT1-SUBJECT2)<10

--MULTIPLICATION
SELECT*FROM STUDENT_INFO WHERE (SUBJECT1*SUBJECT2)>100

--DIVISION
SELECT*FROM STUDENT_INFO WHERE ((SUBJECT1+SUBJECT2)/2)>50

--MODULO//REMENDER
SELECT*FROM STUDENT_INFO WHERE (SUBJECT1%SUBJECT2)>10







