CREATE DATABASE MAHI_TUTORIAL
USE MAHI_TUTORIAL
CREATE TABLE STUDENT(R_NO INT PRIMARY KEY,NAME VARCHAR(222),EMAIL VARCHAR(50),ADDRESS VARCHAR(58))
INSERT INTO STUDENT VALUES(1,'MAHI','MAHI@2GMAIL.COM','SHEVGAON')
INSERT INTO STUDENT VALUES(2,'SANKET','SANKET@2GMAIL.COM','DELHI'),(3,'PRATIK','PRATIK@2GMAIL.COM','DHULE')

ALTER TABLE STUDENT ADD MOBILE VARCHAR(10)
SELECT*FROM STUDENT
SELECT R_NO FROM STUDENT

ALTER TABLE STUDENT DROP COLUMN MOBILE
SELECT*FROM STUDENT
--UPDATE=ALREADY EXIST VALUE IS CHANGE
UPDATE STUDENT SET ADDRESS='PUNE' WHERE R_NO=1

--DELETE=REMOVING TOUPLE FROM TABLE
DELETE FROM STUDENT WHERE R_NO=3

--TRUNCATE =REMOVING EACH AND EVERY CONTENT IN TABLE EXCEPT ITS ATRIBUTE
TRUNCATE TABLE STUDENT

INSERT INTO STUDENT VALUES(1,'MAHI','MAHI@GMAIL.COM','SHEVGAON')
--DROP=WHOLE TABLE DELETE
DROP TABLE STUDENT 

