--FOREIGN KEY

-- KEY : 

SELECT * FROM STUDENT_ACADMEIC_INFO

--FOREIGN KEY : KEY WHICH TAKE REFERECE FROM PRIMARY_KEY OF ANOTHER TABLE 

DROP TABLE IF EXISTS STUDENT_INFO_BASE_TABLE
GO
CREATE TABLE STUDENT_INFO_BASE_TABLE (
STUDENT_ID INT PRIMARY KEY ,
STUDENT_FIRST_NAME VARCHAR(100),
CITY VARCHAR(100),
)

DROP TABLE IF EXISTS STUDENT_COURSE_INFO
GO
CREATE TABLE STUDENT_COURSE_INFO (
STUDENT_ID INT FOREIGN KEY REFERENCES STUDENT_INFO_BASE_TABLE(STUDENT_ID) ,
STUDENT_COURSE VARCHAR(100)
)


INSERT INTO STUDENT_INFO_BASE_TABLE VALUES(1, 'Sanket',' Pune')
INSERT INTO STUDENT_INFO_BASE_TABLE VALUES(2, 'Apurva','Mumbai')
INSERT INTO STUDENT_INFO_BASE_TABLE VALUES(3, 'Bhushan','Nagpur')

select * from STUDENT_INFO_BASE_TABLE

INSERT INTO STUDENT_COURSE_INFO VALUES(1, 'mechanical')
INSERT INTO STUDENT_COURSE_INFO VALUES(2, 'computer')

select * from STUDENT_INFO_BASE_TABLE
select * from STUDENT_COURSE_INFO

UPDATE SCI SET SCI.STUDENT_ID=1 FROM STUDENT_COURSE_INFO SCI WHERE STUDENT_ID=2

UPDATE SCI SET SCI.STUDENT_ID=10 FROM STUDENT_COURSE_INFO SCI WHERE STUDENT_COURSE='mechanical'




UPDATE SIB SET SIB.STUDENT_ID=2  from STUDENT_INFO_BASE_TABLE SIB WHERE SIB.STUDENT_ID=8