DROP TABLE IF EXISTS EMPLOYEE
GO
CREATE TABLE EMPLOYEE (
    EMPLOYEEID INT PRIMARY KEY,
    EMPLOYEENAME VARCHAR(100),
    ROLE VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    SALARY DECIMAL(18, 2)
);


INSERT INTO EMPLOYEE (EMPLOYEEID, EMPLOYEENAME, ROLE, DEPARTMENT, SALARY) VALUES (1, 'Ravi Kumar', 'Manager', 'Sales', 75000.00);
INSERT INTO EMPLOYEE (EMPLOYEEID, EMPLOYEENAME, ROLE, DEPARTMENT, SALARY) VALUES (2, 'Sita Patel', 'Developer', 'IT', 85000.00);
INSERT INTO EMPLOYEE (EMPLOYEEID, EMPLOYEENAME, ROLE, DEPARTMENT, SALARY) VALUES (3, 'Amit Sharma', 'Analyst', 'Finance', 65000.00);
INSERT INTO EMPLOYEE (EMPLOYEEID, EMPLOYEENAME, ROLE, DEPARTMENT, SALARY) VALUES (4, 'Priya Nair', 'Support', 'Customer Service', 55000.00);
INSERT INTO EMPLOYEE (EMPLOYEEID, EMPLOYEENAME, ROLE, DEPARTMENT, SALARY) VALUES (5, 'Vijay Singh', 'Developer', 'IT', 82000.00);
INSERT INTO EMPLOYEE (EMPLOYEEID, EMPLOYEENAME, ROLE, DEPARTMENT, SALARY) VALUES (6, 'Anita Desai', 'Manager', 'Human Resources', 70000.00);
INSERT INTO EMPLOYEE (EMPLOYEEID, EMPLOYEENAME, ROLE, DEPARTMENT, SALARY) VALUES (7, 'Rohan Mehta', 'Analyst', 'Finance', 68000.00);
INSERT INTO EMPLOYEE (EMPLOYEEID, EMPLOYEENAME, ROLE, DEPARTMENT, SALARY) VALUES (8, 'Kavita Reddy', 'Support', 'Customer Service', 57000.00);
INSERT INTO EMPLOYEE (EMPLOYEEID, EMPLOYEENAME, ROLE, DEPARTMENT, SALARY) VALUES (9, 'Rahul Gupta', 'Developer', 'IT', 83000.00);
INSERT INTO EMPLOYEE (EMPLOYEEID, EMPLOYEENAME, ROLE, DEPARTMENT, SALARY) VALUES (10, 'Sneha Joshi', 'Manager', 'Sales', 76000.00);
INSERT INTO EMPLOYEE (EMPLOYEEID, EMPLOYEENAME, ROLE, DEPARTMENT, SALARY) VALUES (11, 'Arjun Rao', 'Developer', 'Research and Development', 90000.00);
INSERT INTO EMPLOYEE (EMPLOYEEID, EMPLOYEENAME, ROLE, DEPARTMENT, SALARY) VALUES (12, 'Nisha Kapoor', 'Analyst', 'Finance', 69000.00);
INSERT INTO EMPLOYEE (EMPLOYEEID, EMPLOYEENAME, ROLE, DEPARTMENT, SALARY) VALUES (13, 'Rajesh Iyer', 'Support', 'Customer Service', 56000.00);
INSERT INTO EMPLOYEE (EMPLOYEEID, EMPLOYEENAME, ROLE, DEPARTMENT, SALARY) VALUES (14, 'Pooja Verma', 'Manager', 'Human Resources', 71000.00);
INSERT INTO EMPLOYEE (EMPLOYEEID, EMPLOYEENAME, ROLE, DEPARTMENT, SALARY) VALUES (15, 'Naveen Chaudhary', 'Developer', 'Research and Development', 92000.00);
SELECT*FROM EMPLOYEE E

SELECT SUM(E.SALARY) AS 'SALARY' FROM EMPLOYEE E

--SUM OF SALARY FOR IT DEPERTMENT
SELECT SUM(E.SALARY) FROM EMPLOYEE E WHERE E.DEPARTMENT='IT'

--SUM OF SALARY FOR ROLE ID DEVELOPER ANE IS DEPARTMENT IS IT

SELECT SUM(E.SALARY)FROM EMPLOYEE E WHERE E.ROLE='Developer'AND E.DEPARTMENT='IT'
 
--HOW MANY EMP WORK IN SEME DEPARTMENT THEREFORE TO USE GROUP BY QUERY 
SELECT E.DEPARTMENT, COUNT(E.DEPARTMENT)FROM EMPLOYEE E GROUP BY E.DEPARTMENT

SELECT E.DEPARTMENT,MAX(E.SALARY)
FROM EMPLOYEE E GROUP BY E.DEPARTMENT

--PR ROLE MAXIMUM SALARY PRINT 
SELECT E.ROLE, MAX(E.SALARY)FROM EMPLOYEE E GROUP BY E.ROLE

--5.COUNT OF EMPLOYEE IN EACH ROLE

SELECT E.ROLE,COUNT (E.ROLE) FROM EMPLOYEE E GROUP BY E.ROLE

--ALL DEP PR DEP SAL SUM COOUNT
SELECT E.DEPARTMENT,SUM(E.SALARY)
FROM EMPLOYEE E GROUP BY E.DEPARTMENT

--ONLY IT DEP SAL SUM
SELECT E.DEPARTMENT,SUM(E.SALARY)
FROM EMPLOYEE E GROUP BY E.DEPARTMENT
HAVING E.DEPARTMENT='IT'

--HAVING MADHE GROUP BY CH O/P FILTER KARAYCH ASEL TR HAVING USE KARAYCH
--ITHE WHERE USE NAHI KARAYCH

--**** DEPARTMENT WITH AVG SAL ABOVE 70000
SELECT E.DEPARTMENT,AVG(E.SALARY)
FROM EMPLOYEE E GROUP BY E.DEPARTMENT
HAVING AVG(E.SALARY)>70000

--DEP AND AVG SALRY PRINT KARAYCHI
SELECT E.DEPARTMENT,
AVG(E.SALARY) AS 'AVERAGE SALARY'
FROM EMPLOYEE E
GROUP BY E.DEPARTMENT
HAVING AVG(E.SALARY)>70000
ORDER BY [AVERAGE SALARY] DESC
