DROP TABLE IF EXISTS DEPARTMENT
GO
CREATE TABLE DEPARTMENT
(
DEPARTMENT_ID INT,
DEPARTEMENT_NAME VARCHAR(100)
)



INSERT INTO DEPARTMENT VALUES (1, 'Computer Departement')
INSERT INTO DEPARTMENT VALUES (2, 'IT Departement')
INSERT INTO DEPARTMENT VALUES (3, 'Civil Departement')
INSERT INTO DEPARTMENT VALUES (4, 'Mechanical Departement')
INSERT INTO DEPARTMENT VALUES (5, 'Electrical Departement')

DROP TABLE IF EXISTS STUDENT_INFORMATION
GO
CREATE TABLE STUDENT_INFORMATION
(
STUDENT ID INT,
FIRST NAME VARCHAR(100),
LAST NAME VARCHAR(100),
CITY VARCHAR(100),


DEPARTMENT ID INT

COMPUTER DEPARTEMENT STUDENT

INSERT INTO STUDENT_INFORMATION VALUES(1, 'Rushikesh', 'Pandit, Sangamner, 1)

INSERT INTO STUDENT_INFORMATION VALUES(2, 'Shriram', 'Aghav', 'Newasa', 1)

INSERT INTO STUDENT INFORMATION VALUES(3, Dhushan Patil Akole 1)

IT DEPARTEMENT STUDENT

INSERT INTO STUDENT UNFORMATTON VALUES(4. Priti Hase Sangamner (2)

INSERT INTO STUDENT INFORMATION VALUES (5, Apurva, Shindhe", "Hewasa, 2)

INSERT INTO STUDENT_INFORMATION VALUES (6, Monali', 'Kole', 'Akole, 2)

CIVIL DEPARTEMENT STUDENT

INSERT INTO STUDENT INFORMATION VALUES(7 Saurabh Rashinker Mumbai,3)

INSERT INTO STUDENT INFORMATION vaakash Kakan Beallati 3)

INSERT INTO STUDENT INFORMATION VALUES (9) Mahesh Raut, Purte', 3)

MECHANICAL DEPARTEMENT STUDENT

INSERT INTO STUDENT INFORMATION VALUES (10) Prashant', 'Kumar', 'Ranchi' 4)

121%

INSERT INTO STUDENT INFORMATION VALUES 11. Aditva' Kale Newasa 4)

Messagos

11 zou affected)

Joins.sql-LAPTOP-NNRIBPRZ/HP (69))"

--1 Rushikesh

Pandit

Sangamner

1

4

MEROT

--1 Rushikesh

Pandit

Sangamner

1

5

y

ags XPs disabl

Civil Dep?? ??????

Mechanical Departement

Electrical Departement

SELECT FROM STUDENT DATA

SELECT FROM STUDENT_HOSTEL_INFORMATION SHI

--FIRST NAME, LAST NAME, HOSTEL NAME RECORD NAME

--OUTPUT COLUMN FIRT_NAME, LAST NAME, HASTEL NAME N RECTOR NAME

STUDNET DATA

HOSTE INFO

JOIN

COMMON COLUMN

BASE TABLE COLUMN REFER TO REFRENCE TABLE

HOSTEL ID

SELECT FROM STUDENT_DATA SD

INNER JOIN STUDENT_HOSTEL_INFORMATION SHI ON SD. HOSTEL_ID=