USE MAHI_TUTORIAL
SELECT*FROM STUDENT_INFO 

--AND OPERATOR
SELECT*FROM STUDENT_INFO WHERE SUBJECT1>50 AND AGE>23

--OR OPERATOR
SELECT*FROM STUDENT_INFO WHERE SUBJECT1>50 OR AGE>23

--NOT
SELECT*FROM STUDENT_INFO WHERE NOT SUBJECT1>50 

