CREATE TABLE STUDENT_MORE_INFORMATION11(STUDENT_ID INT,FATHER_NAME VARCHAR(200), MOTHER_NAME VARCHAR(200), CITY VARCHAR(200) )

INSERT INTO STUDENT_MORE_INFORMATION11 VALUES(1, 'RAM', 'RUPA', 'PUNE')

INSERT INTO STUDENT_MORE_INFORMATION11 VALUES(2, 'SHAM', 'DIPA', 'MUMBAI')

INSERT INTO STUDENT_MORE_INFORMATION11 VALUES(3, 'SANTOSH', 'JAYA', 'SANGAMNER')

INSERT INTO STUDENT_MORE_INFORMATION11 VALUES(4, 'RAJENDARA', 'USHA', 'SANGAMNER')

INSERT INTO STUDENT_MORE_INFORMATION11 VALUES(5, 'JITENDRA', 'KOMAL', 'BANGLORE') 

INSERT INTO STUDENT_MORE_INFORMATION11 VALUES(6, 'LAXMAN', 'JYOTI', 'NASHIK')

INSERT INTO STUDENT_MORE_INFORMATION11 VALUES (6, 'LAXMAN', 'JYOTI', 'NASHIK')

--write query to find studnet whose salary in not maximum salary without sub-query

--write query to find out second maximum salary

--write query to find studnet whose salary in not maximum salary with sub-query

--WRITE A QUERY TO FIND OUT STDENT WHOS CITY IS PUNE
SELECT FROM STUDENT_MORE_INFORMATION11 SI

--QUE: MAXIMUM SALARY

SELECT MAX(SI. SALARY) FROM STUDENT_MORE_INFORMATION11 SI

--QUE: WRITE QUERY TO FIND STUDNET HAVING MAXIMUM SALARY

SELECT FROM STUDENT_MORE_INFORMATION11 SI WHERE SI SALARY

(SELECT MAX(SI. SALARY) FROM STUDENT_MORE_INFORMATION11
QUE: WRITE QUERY TO FIND STUDENT WHOSE SALARY IS NOT MAXIMUM SALARY

SELECT MAX(SI. SALARY) FROM STUDENT_MORE_INFORMATION11

SELECT FROM STUDENT_INFORMATION SI WHERE SI. SALARY 1=65000
SELECT MAX(SI SALARY FROM STUDENT INFORMATION SI

SELECT FROM STUDENT_INFORMATION SI

WHERE SI SALARY 1=(SELECT MAX(SI.SALARY) FROM STUDENT_INFORMATION SI)

QUE: WRITE QUERY TO FIND SECOD MAX SALARY--



SELECT MAX(SI. SALARY) FROM STUDENT_INFORMATION SI WHERE SI SALARY (SELECT MAX(SI. SALARY) FROM STUDENT_INFORMATION SI)
L.VSOBLEM ASUS (57)

Object Explorer

SELECT MAX(SI.SALARY FROM STUDENT INFORMATION SI

SELECT FROM STUDENT_INFORMATION SI

WHERE SI. SALARY (SELECT MAX(SI.SALARY) FROM STUDENT_INFORMATION SI) I

QUE: WRITE QUERY TO FIND SECOD MAX SALARY--

OUTPUE: 55000

SELECT MAX(SI. SALARY FROM STUDENT_INFORMATION SI

WHERE SI SALARY (SELECT MAX(SI. SALARY) FROM STUDENT_INFORMATION SI)

QUE: WRITE QUERY TO FIND STUDNET HAVING SECOND MAX SALARY -

-OUTPUT: SHRRIRAM KALE
QUE: WRITE QUERY TO FIND SECOD MAX SALARY--

OUTPUE: 55000

Object Explorer

SELECT MAX(SI SALARY) FROM STUDENT_INFORMATION SI

WHERE SI.SALARY 1=(SELECT MAX(SI.SALARY) FROM STUDENT_INFORMATION SI )

QUE: WRITE QUERY TO FIND STUDNET HAVING SECOND MAX SALARY

OUTPUT: SHRRIRAM KALE

SELECT FROM STUDENT INFORMATION SI WHERE SI SALARY SELECT MAX(SI SALARY FROM STUDENT_INFORMATION SI WHERE SI SALARY (SELECT MAX(SI, SALARY FROM STUDENT_INFORMATION SI