USE MAHI_TUTORIAL
SELECT*FROM STUDENT_INFO 

--A IS STRART 
SELECT*FROM STUDENT_INFO WHERE NAME LIKE'A%'

--T AS LAST
SELECT*FROM STUDENT_INFO WHERE NAME LIKE'%T'

--CHAE A IS AVAILABLE OR NOTHING
SELECT*FROM STUDENT_INFO WHERE NAME LIKE'%A%'

--A AS 3RD CHAR
SELECT*FROM STUDENT_INFO WHERE NAME LIKE'___A%'

--START WITH U AND NAME CONSISTING WITH ATLEASRT 4 CHAR
SELECT*FROM STUDENT_INFO WHERE NAME LIKE'G___%'

--START WITH A AND END WIHT N
SELECT*FROM STUDENT_INFO WHERE NAME LIKE'A%N'

SELECT*FROM STUDENT_INFO WHERE NAME LIKE'A___N'

--NOT LIKE
SELECT*FROM STUDENT_INFO WHERE NAME NOT LIKE'A%'
SELECT*FROM STUDENT_INFO WHERE NAME NOT LIKE'%__U'



