USE MAHI_TUTORIAL
CREATE TABLE STUDENT_INFO (R_NO INT PRIMARY KEY,NAME VARCHAR(200),AGE INT,SUBJECT1 INT,SUBJECT2 INT)
INSERT INTO STUDENT_INFO VALUES(1,'MAHI',22,54,55),(2,'SANKET',23,30,60),(3,'ISHA',28,48,50),(4,'GURU',21,45,45),(5,'ARJUN',24,59,40)
SELECT * FROM STUDENT_INFO

--EQUAL OPERATOR
SELECT*FROM STUDENT_INFO WHERE R_NO=2
SELECT*FROM STUDENT_INFO WHERE AGE=21

SELECT*FROM STUDENT

--GREATER THAN
SELECT*FROM STUDENT_INFO WHERE AGE>23

--LESS THAN
SELECT*FROM STUDENT_INFO WHERE AGE<23
SELECT*FROM STUDENT_INFO

--GERATER THAN OR EQULAL TO(>=)
SELECT*FROM STUDENT_INFO WHERE AGE>=23

--LESS THAN OR EQUAL TO(<=)
SELECT*FROM STUDENT_INFO WHERE AGE<=23
SELECT*FROM STUDENT_INFO 

--NOT EQUAL TO(<>)
SELECT*FROM STUDENT_INFO WHERE AGE<>23
SELECT*FROM STUDENT_INFO


