CREATE DATABASE XYZ_COMP
DROP DATABASE XYZ_COMP

USE XYZ_COMP

CREATE TABLE EMPLOYEE_INFO(
	ID INT PRIMARY KEY,
	NAME VARCHAR(30),
	SALARY INT NOT NULL
)

INSERT INTO EMPLOYEE_INFO 
(ID,NAME,SALARY)
VALUES
(1,'AMAN',25000),
(2,'BOB',30000),
(3,'CASEY',40000)

SELECT * FROM EMPLOYEE_INFO
